name: Hello World Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  Workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    services:
      image: postgres:15
      env:
        POSTGRES_USER: siddique
        POSTGRES_PASSWORD: password
        POSTGRES_DB: database_test
      ports:
        - 5432:5432
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup node js
        uses: actions/setup-node@v4
        with:
          node-version: '24.4.1'
      - name: install dependencies
        run: npm install
      - name: run migrations
        run: npx sequelize-cli db:migrate --env test
      - name: run tests
        run: npm test
